cc_library(
    name = 'dict',
    srcs = [
        'binary_dict.cc',
        'binary_dict_dumper.cc',
        'dict_manager.cc',
    ],
    hdrs = [
        'binary_dict.h',
        'binary_dict_dumper.h',
        'dict.h',
        'dict_manager.h',
    ],
    visibility = ["//visibility:public"],
)
